defmodule Chronodash.Repo.Migrations.UpdateMetricsPkUpsert do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:observations)

    create table(:observations, primary_key: false) do
      add :location_id, :uuid, null: false, primary_key: true
      add :metric_type, :text, null: false, primary_key: true
      add :timestamp, :utc_datetime_usec, null: false, primary_key: true
      add :value, :float, null: false
      add :unit, :text
      add :source, :text, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "SELECT create_hypertable('observations', 'timestamp');"

    alter table(:observations) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "observations_location_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:locations, [:name], name: "locations_name_index")
  end

  def down do
    drop constraint("observations", "observations_pkey")

    drop_if_exists unique_index(:locations, [:name], name: "locations_name_index")

    alter table(:observations) do
      modify :location_id, :uuid, null: true
      modify :metric_type, :text
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    execute("ALTER TABLE \"observations\" ADD PRIMARY KEY (id, timestamp)")
  end
end
