# Elixir backend that analyzes meteoFIX data, provides insights, and integrates with Grafana.

# Copyright (C) 2026 Santiago Garea Cidre, Paula Carril Gontán, and Saúl Zas Carballal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see [GNU GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).

defmodule Chronodash.Repo.Migrations.UpdateMetricsPkUpsert do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:observations)

    create table(:observations, primary_key: false) do
      add :location_id, :uuid, null: false, primary_key: true
      add :metric_type, :text, null: false, primary_key: true
      add :timestamp, :utc_datetime_usec, null: false, primary_key: true
      add :value, :float, null: false
      add :unit, :text
      add :source, :text, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "SELECT create_hypertable('observations', 'timestamp');"

    alter table(:observations) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "observations_location_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:locations, [:name], name: "locations_name_index")
  end

  def down do
    drop constraint("observations", "observations_pkey")

    drop_if_exists unique_index(:locations, [:name], name: "locations_name_index")

    alter table(:observations) do
      modify :location_id, :uuid, null: true
      modify :metric_type, :text
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    execute("ALTER TABLE \"observations\" ADD PRIMARY KEY (id, timestamp)")
  end
end
