defmodule Chronodash.Repo.Migrations.CreateMetricsFinal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"

    create table(:observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :timestamp, :utc_datetime_usec, null: false, primary_key: true
      add :metric_type, :text, null: false
      add :value, :float, null: false
      add :unit, :text
      add :source, :text, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id, :uuid
    end

    execute "SELECT create_hypertable('observations', 'timestamp');"

    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:observations) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "observations_location_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:locations) do
      add :name, :text, null: false
      add :latitude, :float, null: false
      add :longitude, :float, null: false
      add :external_id, :text

      add :inserted_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :timestamptz,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:locations) do
      remove :updated_at
      remove :inserted_at
      remove :external_id
      remove :longitude
      remove :latitude
      remove :name
    end

    drop constraint(:observations, "observations_location_id_fkey")

    alter table(:observations) do
      modify :location_id, :uuid
    end

    drop table(:locations)

    drop table(:observations)
  end
end
