{
 "title": "Extreme Weather",
 "tags": [
  "meteosix",
  "weather",
  "alertas",
  "extremos",
  "geomap"
 ],
 "time": { "from": "now-6h", "to": "now+24h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "location", "query": "SELECT name FROM locations" }
  ]
 },
 "panels": [
  {
   "title": "Extreme Precipitations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"precipitation_amount\"}",
     "legendFormat": "Precipitación"
    }
   ]
  },
  {
   "title": "Snow Acumulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"snow_level\"}",
     "legendFormat": "Acumulación de nieve"
    }
   ]
  },
  {
   "title": "Strong Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"wind_module\"}",
     "legendFormat": "Viento"
    }
   ]
  },
  {
   "title": "Max. Precipitations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(chronodash_meteosix_wrf_observation_value{variable=\"precipitation_amount\"})",
     "legendFormat": "Máx. Precipitación"
    }
   ]
  },
  {
   "title": "Max. Snow Acumulation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(chronodash_meteosix_wrf_observation_value{variable=\"snow_level\"})",
     "legendFormat": "Máx. Nieve"
    }
   ]
  },
  {
   "title": "Max. Wind Registered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(chronodash_meteosix_wrf_observation_value{variable=\"wind_module\"})",
     "legendFormat": "Máx. Viento"
    }
   ]
  }
 ]
}