{
 "title": "Today Weather",
 "tags": [
  "meteosix",
  "weather"
 ],
 "time": { "from": "now", "to": "now+24h" },
 "templating": {
  "list": [
   { "name": "location", "query": "SELECT name FROM locations" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"precipitation_amount\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"wind_module\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"relative_humidity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather Forecast",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"temperature\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"wind_module\"}",
     "legendFormat": "wind"
    },
    {
     "expr": "chronodash_meteosix_wrf_observation_value{variable=\"precipitation_amount\"}",
     "legendFormat": "precipitation"
    }
   ]
  },
  {
   "title": "Sky State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp as time,\n  value as \"Sky State\",\n  locations.name as location\nFROM\n  observations\nJOIN\n  locations ON observations.location_id = locations.id\nWHERE\n  metric_type = 'sky_state'\n  AND locations.name IN ($location)\n  AND $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  }
 ]
}